@apiUrl = http://localhost:3000/api/v1
@taskUrl = {{apiUrl}}/tasks

POST {{taskUrl}}
Content-Type: application/json

{
    "task" : "Least",
    "hour" : 30,
    "type" : "bad"
}

###
GET {{taskUrl}}

###
PATCH {{taskUrl}}/698fc1f355d3f3fbe0eb3ece
Content-Type: application/json

{
    "hour" : 100,
    "type" : "good"
}


###
DELETE {{taskUrl}}/698fc902f21219efeb86c8cf