@apiUrl = http://localhost:3000/api/v1
@taskUrl = {{apiUrl}}/tasks

POST {{taskUrl}}
Content-Type: application/json

{
    "task" : "Database Task",
    "hour" : 90,
    "type" : "good"
}

###
GET {{taskUrl}}

###
PATCH {{taskUrl}}/698fc1e9e832f26269904cec
Content-Type: application/json

{
    "hour" : 100
}


###
DELETE {{taskUrl}}/2RhZJA